### ISSUE TITLE
Translation via Transifex

### ISSUE THREAD

**Issue by Alir3z4** [sijad/flarum-ext-persian#2]
I have setup a transifex project to continue translating.

Repo: https://www.transifex.com/alir3z4/flarum-extension-persian

It will be automatically updated whenever the English locales get updated.
I have sent an invite to your email to be a maintainer on the translation project.

**Comment by sijad** [comment]
nice, maybe we should add that link to README too?

**Comment by Alir3z4** [comment]
Sure we can.
I'll make a pull request for README changes as well.

Should I modify the readme in Farsi or English ?

**Comment by sijad** [comment]
or maybe a CONTRIBUTING.md would be better

**Comment by sijad** [comment]
I guess it's better to add a CONTRIBUTING.md and add a link to that file in README.md instead, both in Persian and English.

I really appreciate your help. Thanks!
